server:
  port: 8065
  name: Ms Production

spring:
  application:
    name: ms-production
  data:
    mongodb:
      auto-index-creation: true
      uri: mongodb://localhost:27017/fiap-production?retryWrites=true&w=majority
  main:
    allow-bean-definition-overriding: true

springdoc:
  swagger-ui:
    path: /user-api-docs.html
  paths-to-match: /**/user/**